### PR TITLE
statsd for elasticsearch 6.3.1

### PR DESCRIPTION
**Pull request by shekhar8617**
statsd for elasticsearch 6.3.1

### CODE REVIEW

**Review by elezar — APPROVED** [review]
It looks OK to me, but someone like @mpereira definitely has more experience here.

**Comment by mpereira** [comment]
Thanks for the PR @shekhar8617.

Could you also open a PR [upstream](https://github.com/Automattic/elasticsearch-statsd-plugin/pulls)?

Unless time is pressing, [the way we usually handle statsd plugin version bumps](https://github.com/mesosphere/dcos-commons/blob/master/frameworks/elastic/upgrade_base_tech.md) is:
1. Open PR upstream
2. Wait for PR to get merged
3. Merge (--ff) upstream master to our master
4. Create release on our repo

This is so that our fork is (ideally) just the same as upstream.

**Review by elezar — CHANGES_REQUESTED** [review]
Please follow the process as proposed by @mpereira.

**Comment by shekhar8617** [comment]
I have raised upstream PR  for elasticsearch-statsd https://github.com/Automattic/elasticsearch-statsd-plugin/pull/29 @elezar @mpereira

**Comment by mpereira** [comment]
Thanks @shekhar8617.

**Comment by shekhar8617** [comment]
Hi @mpereira , @elezar  upstream PR https://github.com/Automattic/elasticsearch-statsd-plugin/pull/29 has been merge to master.

**Pull request closed without merging**
